[package]
name = "atcoder"
version = "0.1.0"
authors = ["s4i <yasasisanoriyuu123@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
